version: '3.1'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php
    php:
        build: ./images/php
        links:
            - mysql
        volumes:
            - ./www:/var/www
    mysql:
      build: ./mysql
      container_name: mysql
      working_dir: /application
      volumes:
        - ./mysql:/application
      environment:
        - MYSQL_ROOT_PASSWORD=test112233
        - MYSQL_DATABASE=test
        - MYSQL_USER=testuser
        - MYSQL_PASSWORD=123456
      ports:
        - "3306:3306"
volumes:
  mysql: